### ISSUE TITLE
onPermissionDenied() never called

### ISSUE THREAD

**Issue by liutingdu** [canelmas/let#14]
I have @AskPermission in my fragment that implemented `RuntimePermissionListener`, something like this:

```
@AskPermission({CAMERA, WRITE_EXTERNAL_STORAGE}) private void startCamera() {
        //Display camera view
}
```

It works when the permissions got granted, but when I tried to handle denied situation, `onPermissionDenied()` never gets called . Just wonder when it calls `onPermissionDenied()`?

**Comment by canelmas** [comment]
Hi @liutingdu, are you certain that it's not the `onShowPermissionRationale` case instead of `onPermissionDenied`?

**Comment by liutingdu** [comment]
Yes, `onShowPermissionRationale` was called but `onPermissionDenied` wasn't. Sorry I'm not able to provide more details as I didn't test it again, I'll close this issue in this case. Thanks anyway!
