### ISSUE TITLE
Load time

### ISSUE THREAD

**Issue by moelfassi** [canelmas/let#6]
The first load is slow on my Moto G 2014, take about 10 seconds.
is there any way to speed it up?

**Comment by canelmas** [comment]
@elcampnou what do you mean by first load is slow?  Did you implement into your project or just trying the sample? When and where do you exactly experience this slowness?

**Comment by moelfassi** [comment]
its when i compile the project and launch it for the first time, i created a new project with only 2 buttons plus your library

**Comment by moelfassi** [comment]
Don't worry about it, its just a problem related Android 2.0.

Good job!
